services:
  - type: web
    name: datndirtywave-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_RETURN_URL
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: LOOKUP_MAIL_FROM
        sync: false
      - key: ASSISTANT_ENABLED
        value: false
      - key: ASSISTANT_DEMO_MODE
        value: true